[[Jansson]]
arch = "aarch64"
git-tree-sha1 = "bba241a54126d920d3e10ec75914dd3c93cb4e39"
os = "macos"

    [[Jansson.download]]
    sha256 = "1a7d2bc875f287c5070c7a9002de480eff707cacbc48975cf2cc681b82a9cbf7"
    url = "https://github.com/JuliaBinaryWrappers/Jansson_jll.jl/releases/download/Jansson-v2.14.1+0/Jansson.v2.14.1.aarch64-apple-darwin.tar.gz"
[[Jansson]]
arch = "aarch64"
git-tree-sha1 = "9637300177f6cef64c90f873b16dfbbf2b5c2d89"
libc = "glibc"
os = "linux"

    [[Jansson.download]]
    sha256 = "57a4f04b9479a38756c29253bae4e240ba2e41e6c52ce57aedd772d92170c64d"
    url = "https://github.com/JuliaBinaryWrappers/Jansson_jll.jl/releases/download/Jansson-v2.14.1+0/Jansson.v2.14.1.aarch64-linux-gnu.tar.gz"
[[Jansson]]
arch = "aarch64"
git-tree-sha1 = "bf472793cd91f50ae0a9168441f7b159102fe25e"
libc = "musl"
os = "linux"

    [[Jansson.download]]
    sha256 = "fb08e1b7ba6ae8ed8a569cce96d4306ffc631df8f4d94cb4c4d43c614b291e14"
    url = "https://github.com/JuliaBinaryWrappers/Jansson_jll.jl/releases/download/Jansson-v2.14.1+0/Jansson.v2.14.1.aarch64-linux-musl.tar.gz"
[[Jansson]]
arch = "aarch64"
git-tree-sha1 = "e0540d73da8a1510fe674b4c66e4f01effe6cb99"
os = "freebsd"

    [[Jansson.download]]
    sha256 = "38bc2acd115ae5b8a06109a75bc796b862915ef545c5132b70a96fc1dac177f6"
    url = "https://github.com/JuliaBinaryWrappers/Jansson_jll.jl/releases/download/Jansson-v2.14.1+0/Jansson.v2.14.1.aarch64-unknown-freebsd.tar.gz"
[[Jansson]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "97a113109b14a261e5f35c777240ff9eef92d1a2"
libc = "glibc"
os = "linux"

    [[Jansson.download]]
    sha256 = "9a7d73195fc5696831eede137238d60cfddc623a924ad28d647e3dbc48f2b045"
    url = "https://github.com/JuliaBinaryWrappers/Jansson_jll.jl/releases/download/Jansson-v2.14.1+0/Jansson.v2.14.1.armv6l-linux-gnueabihf.tar.gz"
[[Jansson]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "317294e72f1ea6ff655f7b66d9f0142a2661f37c"
libc = "musl"
os = "linux"

    [[Jansson.download]]
    sha256 = "55747f9074b656a670f8fa4ff52a0169b11f43d9d891b27ddfa5eb636949d667"
    url = "https://github.com/JuliaBinaryWrappers/Jansson_jll.jl/releases/download/Jansson-v2.14.1+0/Jansson.v2.14.1.armv6l-linux-musleabihf.tar.gz"
[[Jansson]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fd1974971235b503f508d988c9001cd82e41004f"
libc = "glibc"
os = "linux"

    [[Jansson.download]]
    sha256 = "47ed5a48e221ed65c629a265356d0e0b2c9abca47207f437e28274c254ae4983"
    url = "https://github.com/JuliaBinaryWrappers/Jansson_jll.jl/releases/download/Jansson-v2.14.1+0/Jansson.v2.14.1.armv7l-linux-gnueabihf.tar.gz"
[[Jansson]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d2f80fdf3c8afea8c9168482d7163ce04c4c39da"
libc = "musl"
os = "linux"

    [[Jansson.download]]
    sha256 = "80b75768afea16cd67b7475bccc3e8eb51500e53791a07c77af56252b6dfed9c"
    url = "https://github.com/JuliaBinaryWrappers/Jansson_jll.jl/releases/download/Jansson-v2.14.1+0/Jansson.v2.14.1.armv7l-linux-musleabihf.tar.gz"
[[Jansson]]
arch = "i686"
git-tree-sha1 = "7c756d7bdb833a9560e6955215b838e33ed07294"
libc = "glibc"
os = "linux"

    [[Jansson.download]]
    sha256 = "537698fb71ff6655e6bbb526ef13e6f12d60fc0c3f4bd9601062fa2ac31b1f4e"
    url = "https://github.com/JuliaBinaryWrappers/Jansson_jll.jl/releases/download/Jansson-v2.14.1+0/Jansson.v2.14.1.i686-linux-gnu.tar.gz"
[[Jansson]]
arch = "i686"
git-tree-sha1 = "bfd2e120e0d0e4e812c3c74830181a3b005f12d8"
libc = "musl"
os = "linux"

    [[Jansson.download]]
    sha256 = "f122d2b9281b8409270c43e64b6e413ab1e53454432a92aaa198350382cfbff3"
    url = "https://github.com/JuliaBinaryWrappers/Jansson_jll.jl/releases/download/Jansson-v2.14.1+0/Jansson.v2.14.1.i686-linux-musl.tar.gz"
[[Jansson]]
arch = "i686"
git-tree-sha1 = "9fb610a16b9af78244702b4d97cbfffa7ed6a9bc"
os = "windows"

    [[Jansson.download]]
    sha256 = "0aaf196e2396146531f8e84ccf4ce6fdcc8be5f5e5c6f3cdfba034df5da01886"
    url = "https://github.com/JuliaBinaryWrappers/Jansson_jll.jl/releases/download/Jansson-v2.14.1+0/Jansson.v2.14.1.i686-w64-mingw32.tar.gz"
[[Jansson]]
arch = "powerpc64le"
git-tree-sha1 = "580b87764a26430dcf60dab47601466f34c8baa5"
libc = "glibc"
os = "linux"

    [[Jansson.download]]
    sha256 = "b30a675ae778d93e410a65a9e8c4f272f3392722f88cff3a72f0c0d47cacd7df"
    url = "https://github.com/JuliaBinaryWrappers/Jansson_jll.jl/releases/download/Jansson-v2.14.1+0/Jansson.v2.14.1.powerpc64le-linux-gnu.tar.gz"
[[Jansson]]
arch = "riscv64"
git-tree-sha1 = "ffac1899f978437b7b3fcb720e574098c1a86d1a"
libc = "glibc"
os = "linux"

    [[Jansson.download]]
    sha256 = "b73c946034ebd55946bac992238837d2dfc92de85151b91c14530ac17518219e"
    url = "https://github.com/JuliaBinaryWrappers/Jansson_jll.jl/releases/download/Jansson-v2.14.1+0/Jansson.v2.14.1.riscv64-linux-gnu.tar.gz"
[[Jansson]]
arch = "x86_64"
git-tree-sha1 = "57eaa3fe044d2c241266c75e9d90705633c298f4"
os = "macos"

    [[Jansson.download]]
    sha256 = "71ab3afdc51b4d49cb3fa6e73979d095d0dd7b4e167a6f62477eca7c7e432bc3"
    url = "https://github.com/JuliaBinaryWrappers/Jansson_jll.jl/releases/download/Jansson-v2.14.1+0/Jansson.v2.14.1.x86_64-apple-darwin.tar.gz"
[[Jansson]]
arch = "x86_64"
git-tree-sha1 = "5dae295ead963ac74d4df0103944e146d396a4fd"
libc = "glibc"
os = "linux"

    [[Jansson.download]]
    sha256 = "3fd0476051167ada1f0418c3311d95c9aa2d6efb62416882a2f16e7f205a1101"
    url = "https://github.com/JuliaBinaryWrappers/Jansson_jll.jl/releases/download/Jansson-v2.14.1+0/Jansson.v2.14.1.x86_64-linux-gnu.tar.gz"
[[Jansson]]
arch = "x86_64"
git-tree-sha1 = "13a7edf65c73e6c9dbadd340f6b4f81f59740936"
libc = "musl"
os = "linux"

    [[Jansson.download]]
    sha256 = "2614d65b3f701ffa2ee6cb06e8bb81de4808643bb3954285d51bd014dc820351"
    url = "https://github.com/JuliaBinaryWrappers/Jansson_jll.jl/releases/download/Jansson-v2.14.1+0/Jansson.v2.14.1.x86_64-linux-musl.tar.gz"
[[Jansson]]
arch = "x86_64"
git-tree-sha1 = "324a3acfb7ba71b1e508118dcca25ea3566427db"
os = "freebsd"

    [[Jansson.download]]
    sha256 = "4d1d5ac9189ce48b85772c491f5f54f6633012272ad268d2dfe34354bb1d9fc0"
    url = "https://github.com/JuliaBinaryWrappers/Jansson_jll.jl/releases/download/Jansson-v2.14.1+0/Jansson.v2.14.1.x86_64-unknown-freebsd.tar.gz"
[[Jansson]]
arch = "x86_64"
git-tree-sha1 = "45f21f9b2ac3f9451a7c8f133b9de85438b3011a"
os = "windows"

    [[Jansson.download]]
    sha256 = "f36a17f4418ba7beaf97e481e489b68d06173f0f5b8010862a80f1225df388e0"
    url = "https://github.com/JuliaBinaryWrappers/Jansson_jll.jl/releases/download/Jansson-v2.14.1+0/Jansson.v2.14.1.x86_64-w64-mingw32.tar.gz"
